version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  target-branch: crates-update
  ignore:
  - dependency-name: simplelog
    versions:
    - 0.9.0
